name: guita_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.8
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/

  fonts:
    - family: KoddiUDOnGothic-Regular
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-Regular.ttf
        
    - family: KoddiUDOnGothic-Bold
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-Bold.ttf
          weight: 700

    - family: KoddiUDOnGothic-ExtraBold
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-ExtraBold.ttf
          weight: 800
